/**
 * API helpers — success envelope `{ success: true, data }` (plan §2, §26)
 * and the central error handler wrapper. Route handlers throw AppError;
 * this wrapper converts anything into the safe error envelope.
 */
import { NextResponse, type NextRequest } from "next/server";
import { AppError, toErrorBody } from "./errors";

export function ok<T>(data: T, init?: ResponseInit): NextResponse {
  return NextResponse.json({ success: true, data }, init);
}

export function created<T>(data: T): NextResponse {
  return NextResponse.json({ success: true, data }, { status: 201 });
}

export function noContent(): NextResponse {
  return new NextResponse(null, { status: 204 });
}

export function toErrorResponse(error: unknown): NextResponse {
  const body = toErrorBody(error);
  const status = isStatus(body.code);
  return NextResponse.json({ success: false, error: body }, { status });
}

function isStatus(code: string): number {
  switch (code) {
    case "VALIDATION_ERROR":
    case "PAYLOAD_TOO_LARGE":
      return 400;
    case "UNAUTHORIZED":
      return 401;
    case "FORBIDDEN":
      return 403;
    case "NOT_FOUND":
      return 404;
    case "CONFLICT":
      return 409;
    case "RATE_LIMITED":
      return 429;
    case "DEPENDENCY_UNAVAILABLE":
      return 503;
    default:
      return 500;
  }
}

/**
 * Context passed to API handlers. Next.js passes its own RouteContext
 * (generated by typegen); we accept a structural superset so library code
 * never depends on generated global types.
 */
export interface ApiHandlerContext {
  params: Promise<Record<string, string | string[]>>;
}

/** Signature compatible with Next.js Route Handlers (Next 16). */
export type ApiHandler = (req: NextRequest, ctx: ApiHandlerContext) => Promise<Response>;

/** Wraps a handler so all errors flow through the central error handler. */
export function withApiHandler(handler: ApiHandler): ApiHandler {
  return async (req, ctx) => {
    try {
      return await handler(req, ctx);
    } catch (error) {
      return toErrorResponse(error);
    }
  };
}

export interface ReadJsonOptions {
  /** Allow-list of top-level fields; unknown fields → 400 (plan §26). */
  allowedFields?: string[];
  /** Max raw body size in bytes (default 64 KB). */
  maxLength?: number;
}

/**
 * Parses + validates a JSON request body.
 * Rejects: oversized bodies, malformed JSON, non-objects, unknown fields.
 */
export async function readJson(
  req: NextRequest,
  options: ReadJsonOptions = {}
): Promise<Record<string, unknown>> {
  const maxLength = options.maxLength ?? 64 * 1024;
  const text = await req.text();
  if (text.length > maxLength) {
    throw AppError.validation("Request body is too large.");
  }
  if (!text.trim()) {
    throw AppError.validation("A request body is required.");
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    throw AppError.validation("The request body is not valid JSON.");
  }

  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    throw AppError.validation("The request body must be a JSON object.");
  }

  const record = parsed as Record<string, unknown>;
  if (options.allowedFields) {
    const unknownFields = Object.keys(record).filter(
      (key) => !options.allowedFields!.includes(key)
    );
    if (unknownFields.length > 0) {
      throw AppError.validation(
        `Unknown field${unknownFields.length > 1 ? "s" : ""}: ${unknownFields.join(", ")}.`,
        { unknownFields }
      );
    }
  }

  return record;
}
